name: linkup
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mapbox_maps_flutter: ^2.9.0         # Mapbox SDK
  image: ^4.1.3                       # for PNG work you’re doing
  geolocator: ^14.0.1                 # user-location
  permission_handler: ^12.0.0+1         # runtime permissions
  collection: ^1.17.2
  shared_preferences: ^2.2.2
  http: ^1.2.1
  image_picker: ^1.1.0
  bubble: ^1.2.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/transparent_160x160.png    # your badge icon
    - assets/top_us_universities_full.geojson    # ⬅️ NEW (exact path / name)
    - assets/default_pfp.png

