name: linkup
description: "A social mapping application for university communities"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter
  image_cropper: ^9.1.0
  material_design_icons_flutter: ^5.0.6996
  provider: ^6.1.1        # State management
  intl: ^0.18.1           # Internationalization

  # Maps & Location
  mapbox_maps_flutter: ^2.9.0
  geolocator: ^14.0.1
  permission_handler: ^12.0.0+1

  # Data & Storage
  shared_preferences: ^2.2.2
  http: ^1.2.1
  uuid: ^4.0.0
  collection: ^1.17.2

  # Media & Images
  image: ^4.1.3
  image_picker: ^1.1.0
  cached_network_image: ^3.3.0

  # UI Components
  bubble: ^1.2.1
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.0
  badges: ^3.0.0
  flutter_svg: ^2.2.0     # SVG support

  # Forms & Validation
  form_field_validator: ^1.1.0
  email_validator: ^2.1.17
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/
    - assets/logos/
    - assets/top_us_universities_full.geojson
    - assets/default_pfp.png

  fonts:
    - family: LuckiestGuy
      fonts:
        - asset: assets/fonts/LuckiestGuy-Regular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
